"""add service types

Revision ID: 7f1c3cad8ee7
Revises: ed7ae417d004
Create Date: 2026-02-10 16:16:09.817146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1c3cad8ee7'
down_revision: Union[str, Sequence[str], None] = 'ed7ae417d004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_types_tenant_id'), 'service_types', ['tenant_id'], unique=False)
    op.create_index(
        'ix_service_types_tenant_name_unique',
        'service_types',
        ['tenant_id', 'name'],
        unique=True,
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_service_type_id'), 'checklist_items', ['service_type_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_tenant_id'), 'checklist_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_items_tenant_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_service_type_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index('ix_service_types_tenant_name_unique', table_name='service_types')
    op.drop_index(op.f('ix_service_types_tenant_id'), table_name='service_types')
    op.drop_table('service_types')
    # ### end Alembic commands ###
